---
- name: Copy celery config file
  template:
    src: celeryd.j2
    dest: /etc/default/celeryd
  notify: Restart celery

- name: Copy celery service file
  template:
    src: celery_service.j2
    dest: /etc/systemd/system/celeryd.service
  notify: Restart celery

- name: Copy celery beat service file
  template:
    src: celerybeat_service.j2
    dest: /etc/systemd/system/celerybeatd.service
  notify: Restart celery beat

- name: Create pid file dir
  file: path={{ celery_pid_file_dir }}
    owner={{ celery_user }}
    group={{ celery_group }}
    mode=0774
    state=directory

- name: Enable celery
  systemd:
    name: celeryd
    enabled: yes
    daemon_reload: yes

- name: Enable celery beat
  systemd:
    name: celerybeatd
    enabled: yes
    daemon_reload: yes