# Generated by Django 3.2 on 2022-06-06 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nome descritivo')),
                ('display_text', models.CharField(max_length=128, verbose_name='Texto de exibição')),
            ],
            options={
                'verbose_name': 'Perfil de investidor',
                'verbose_name_plural': 'Perfís de investidor',
            },
        ),
        migrations.CreateModel(
            name='ProfileTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Informações para o usuário')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Teste de perfil de investidor',
                'verbose_name_plural': 'Testes de perfís de investidor',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Texto do teste')),
                ('profile_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investorprofile.profiletest', verbose_name='Teste do perfil')),
            ],
            options={
                'verbose_name': 'Teste',
                'verbose_name_plural': 'Testes',
            },
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Pontução do perfil')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investorprofile.profile', verbose_name='Perfil')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investorprofile.test', verbose_name='Teste')),
            ],
            options={
                'verbose_name': 'Pontuação do teste',
                'verbose_name_plural': 'Pontuação dos testes',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(verbose_name='Texto da questão')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investorprofile.test', verbose_name='Teste do perfil')),
            ],
            options={
                'verbose_name': 'Questão do teste',
                'verbose_name_plural': 'Questões dos testes',
            },
        ),
        migrations.CreateModel(
            name='QuestionAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='Texto da alternativa')),
                ('score', models.IntegerField(verbose_name='Pontuação da alternativa')),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investorprofile.testquestion', verbose_name='Questão do teste')),
            ],
            options={
                'verbose_name': 'Alternativa da questão',
                'verbose_name_plural': 'Alternativas das questões',
            },
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('test_data', models.TextField(verbose_name='Resultado do teste')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investorprofile.profile', verbose_name='Perfil do investidor')),
                ('profile_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investorprofile.profiletest', verbose_name='Teste aplicado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='investidor')),
            ],
            options={
                'verbose_name': 'Perfil de investimento do usuário',
                'verbose_name_plural': 'Perfis de investimento dos usuários',
            },
        ),
        migrations.AddConstraint(
            model_name='testscore',
            constraint=models.UniqueConstraint(fields=('test', 'profile'), name='unique_test_score'),
        ),
    ]
