# Generated by Django 3.2 on 2022-07-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fix_disclaimer_end',
            field=models.BooleanField(default=False, help_text='Por padrão o disclaimer é sempre visível', verbose_name='Fixar disclaimer no final da página'),
        ),
    ]
