# Generated by Django 3.2 on 2022-07-22 20:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_fix_disclaimer_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_us',
            field=tinymce.models.HTMLField(blank=True, help_text='Mostrado na página pública', null=True, verbose_name='Sobre a empresa'),
        ),
        migrations.AddField(
            model_name='company',
            name='abt_us_bkg_color',
            field=models.CharField(choices=[('#000000', 'Preto'), ('#FFFFFF', 'Branco'), ('#F8F9FA', 'Cinza claro')], default='#000000', help_text="Cor da caixa 'Sobre a empresa'", max_length=7, verbose_name='Cor de fundo'),
        ),
        migrations.AddField(
            model_name='company',
            name='abt_us_signup_btn',
            field=models.CharField(default='Abrir uma conta', help_text="Botão mostrado na caixa 'Sobre a empresa'", max_length=50, verbose_name='Texto do botão criar conta'),
        ),
    ]
