---
- name: Update
  apt: update_cache=yes   
   
- name: Installing Redis
  apt: 
    name: redis-server
    state: latest

- name: Enable redis
  systemd:
    name: redis
    enabled: yes
    daemon_reload: yes

- name: Python virtualenv
  apt: 
    name: python3-virtualenv
    state: present