---
- name: Postgres
  apt: 
    name:
      - libpq-dev
      - python3-dev
      - python3-psycopg2
      - build-essential
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: yes 

- name: Create DB instance
  postgresql_db:
    name: "{{db_name}}"
    owner: "{{db_user}}"
  become_user: postgres

- name: Create DB user
  postgresql_user:
    name: "{{db_user}}"
    password: "{{db_pass}}"
  become_user: postgres


