# Generated by Django 3.2 on 2022-06-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=128, verbose_name='Senha/Chave de acess')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('is_active', models.BooleanField(verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Acesso à API',
                'verbose_name_plural': 'Acessos à API',
            },
        ),
        migrations.CreateModel(
            name='CustomInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, verbose_name='accepted')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='key')),
                ('sent', models.DateTimeField(null=True, verbose_name='sent')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENT', 'Cliente'), ('BROKER', 'Gerente de conta'), ('APIACC', 'Acesso à página da API'), ('APIAPP', 'Acesso à API'), ('UNDEF', 'Indefinido')], max_length=6, verbose_name='Papel')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Vencimento')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de erro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Tema escuro'), ('light', 'Tema claro')], default='dark', max_length=5, verbose_name='Tema')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENT', 'Cliente'), ('BROKER', 'Gerente de conta'), ('APIACC', 'Acesso à página da API'), ('APIAPP', 'Acesso à API'), ('UNDEF', 'Indefinido')], max_length=6, verbose_name='Papel')),
            ],
            options={
                'verbose_name': 'Papel do usuário',
                'verbose_name_plural': 'Papéis dos usuários',
            },
        ),
    ]
