---
- hosts: webservers
  become: True
  gather_facts: no
  vars_files:
    - ../host_vars/common.yaml

  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: app
      tags: app
    - role: restart
      tags: restart
