---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Deactivate the default nginx from sites-available
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Copy nginx config file
  template:
    src: "config.j2"
    dest: "/etc/nginx/sites-available/{{ nginx_application_name }}"
  notify: Restart nginx

- name: Copy ssl cretificate crt
  copy:
    src: "ssl/certificates/{{ nginx_ssl_crt_file }}"
    dest: "{{ nginx_ssl_target_folder }}/{{ nginx_ssl_crt_file }}"

- name: Copy ssl cretificate key
  copy:
    src: "ssl/certificates/{{ nginx_ssl_key_file }}"
    dest: "{{ nginx_ssl_target_folder }}/{{ nginx_ssl_key_file }}"

- name: Activate the speedseven site
  file: 
    src: "/etc/nginx/sites-available/{{ nginx_application_name }}"
    dest: "/etc/nginx/sites-enabled/{{ nginx_application_name }}"
    state: link
  notify: Restart nginx


- name: Enable nginx
  systemd:
    name: nginx
    enabled: yes
    daemon_reload: yes

