# Generated by Django 3.2 on 2022-06-06 17:32

import common.validation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import investment.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nome da aplicação')),
                ('display_text', models.CharField(max_length=128, verbose_name='Texto de exibição')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('has_application_settings', models.BooleanField(default=False, editable=False, verbose_name='Configuração de aplicação')),
                ('has_account_settings', models.BooleanField(default=False, editable=False, verbose_name='Configuração de conta')),
                ('settings_related_name', models.CharField(blank=True, editable=False, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Aplicação',
                'verbose_name_plural': 'Aplicações',
            },
        ),
        migrations.CreateModel(
            name='ApplicationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('date_activated', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de ativação')),
                ('date_deactivated', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de desativação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('creation_status', models.CharField(choices=[('CRE', 'Aplicação criada'), ('RUN', 'Criando aplicação'), ('WAI', 'Agendado para criação'), ('REQ', 'Solicitado'), ('ERR', 'Erro')], default='REQ', editable=False, max_length=3, verbose_name='Situação')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.application', verbose_name='Aplicação')),
                ('operator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='app_acc_operator', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Aplicação do cliente',
                'verbose_name_plural': 'Aplicações dos clientes',
            },
        ),
        migrations.CreateModel(
            name='ApplicationOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('OPEN', 'Abertura de conta'), ('DEPO', 'Aporte'), ('WWAL', 'Restage da carteira'), ('WINC', 'Restage do rendimento'), ('INCO', 'Rendimento'), ('CLOS', 'Encerramento de conta')], max_length=4, verbose_name='Tipo de operação')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('balance', models.FloatField(validators=[common.validation.validate_greater_than_zero], verbose_name='Saldo')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Descrição')),
                ('operation_date', models.DateTimeField(verbose_name='Data da operação')),
                ('application_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.applicationaccount', verbose_name='Aplicação')),
                ('operator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Operação de aplicação',
                'verbose_name_plural': 'Operações de aplicação',
                'unique_together': {('application_account', 'operation_date')},
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('ispb', models.IntegerField(blank=True, null=True, verbose_name='ISPB')),
            ],
            options={
                'verbose_name': 'Banco',
            },
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(blank=True, max_length=512, null=True)),
                ('is_automatic', models.BooleanField(default=False, verbose_name='Transferêcia automática')),
                ('operation', models.CharField(choices=[('DEPO', 'Aporte'), ('WWAL', 'Restage da carteira'), ('WINC', 'Restage do rendimento')], max_length=4, verbose_name='Tipo de operação')),
                ('state', models.CharField(choices=[('CREA', 'Criada'), ('WTOP', 'Aguardando operação'), ('WREC', 'Aguardando recibo'), ('FINI', 'Finalizado'), ('ERRO', 'Erro')], default='CREA', max_length=4, verbose_name='Situação')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('date_approved', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='Finalização')),
                ('error_message', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Mensagem de erro')),
                ('display_message', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Observação')),
                ('value', models.FloatField(validators=[common.validation.validate_greater_than_zero], verbose_name='Valor da operação')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to=investment.models.user_receipts_path, verbose_name='Comprovante')),
                ('application_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.applicationaccount', verbose_name='Conta')),
                ('application_operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.applicationop', verbose_name='Operação')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moneytrasfer_approver', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Tranferência de dinheiro',
                'verbose_name_plural': 'Tranferências de dinheiro',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBankAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Mensagem')),
                ('status', models.CharField(blank=True, choices=[('CRE', 'Criado'), ('WAI', 'Aguardando'), ('APP', 'Aprovado'), ('DIS', 'Reprovado')], max_length=3, null=True, verbose_name='Situação')),
                ('bank_branch_number', models.IntegerField(blank=True, null=True, verbose_name='Agência')),
                ('bank_branch_digit', models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígito da agência')),
                ('account_number', models.IntegerField(blank=True, null=True, verbose_name='Número da conta')),
                ('account_digit', models.IntegerField(blank=True, null=True, verbose_name='Dígito da conta')),
                ('main_account', models.BooleanField(default=False, verbose_name='Conta principal')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='investment.bank', verbose_name='Banco')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Conta bancária',
                'verbose_name_plural': 'historical Contas bancárias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Mensagem')),
                ('status', models.CharField(blank=True, choices=[('CRE', 'Criado'), ('WAI', 'Aguardando'), ('APP', 'Aprovado'), ('DIS', 'Reprovado')], max_length=3, null=True, verbose_name='Situação')),
                ('bank_branch_number', models.IntegerField(blank=True, null=True, verbose_name='Agência')),
                ('bank_branch_digit', models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígito da agência')),
                ('account_number', models.IntegerField(blank=True, null=True, verbose_name='Número da conta')),
                ('account_digit', models.IntegerField(blank=True, null=True, verbose_name='Dígito da conta')),
                ('main_account', models.BooleanField(default=False, verbose_name='Conta principal')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.bank', verbose_name='Banco')),
                ('operator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta bancária',
                'verbose_name_plural': 'Contas bancárias',
            },
        ),
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nome do modelo')),
                ('display_text', models.CharField(max_length=128, verbose_name='Texto de exibição')),
                ('app_model_class', models.CharField(max_length=256, verbose_name='Classe do modelo de aplicação')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('operator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Modelo de aplicação',
                'verbose_name_plural': 'Modelos de aplicação',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='application_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.applicationmodel', verbose_name='Modelo de aplicação'),
        ),
        migrations.AddField(
            model_name='application',
            name='operator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.CreateModel(
            name='AccountOpSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateTimeField(verbose_name='Data da operação')),
                ('state', models.CharField(choices=[('WAIT', 'Aguardando'), ('RUNN', 'Executanto'), ('FINI', 'Finalizado'), ('ERRO', 'Erro')], default='WAIT', max_length=4, verbose_name='Situação')),
                ('max_trials', models.PositiveIntegerField(default=3, verbose_name='Máximo de tentativas')),
                ('trial', models.PositiveIntegerField(default=0, verbose_name='Tentativas realizadas')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('last_trial_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última tentativa')),
                ('date_finished', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Finalização')),
                ('error_message', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Mensagem de erro')),
                ('is_automatic', models.BooleanField(default=False, verbose_name='Agendamento automático')),
                ('money_transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investment.moneytransfer', verbose_name='Transferência')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accop_schedule_processor', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
            ],
            options={
                'verbose_name': 'Agendamento de operações',
                'verbose_name_plural': 'Agendamentos de operaçôes',
            },
        ),
    ]
