# Generated by Django 3.2 on 2022-06-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['code'], 'verbose_name': 'Banco'},
        ),
    ]
