# Generated by Django 3.2 on 2022-06-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_alter_bank_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ativa'),
        ),
    ]
