# Generated by Django 3.2 on 2022-06-21 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_application_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneytransfer',
            name='application_operation',
        ),
        migrations.AddField(
            model_name='applicationop',
            name='money_transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.moneytransfer', verbose_name='Operação de transferência'),
        ),
    ]
