# Generated by Django 3.2 on 2022-06-16 21:10

from django.db import migrations, models
import django.db.models.deletion
import investment.interfaces.validators


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_alter_bank_options'),
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('value', models.FloatField(blank=True, null=True, validators=[investment.interfaces.validators.validate_null_or_greate_than_zero], verbose_name='Valor')),
                ('completed', models.BooleanField(default=False, verbose_name='Depósito concluído')),
                ('application_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.applicationaccount', verbose_name='Conta do cliente')),
            ],
        ),
    ]
