# Generated by Django 3.2 on 2022-06-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_application_is_active'),
        ('crowdfunding', '0003_auto_20220619_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PendingDeposit',
            new_name='ApplicationDeposit',
        ),
    ]
