# Generated by Django 3.2 on 2022-06-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0004_rename_pendingdeposit_applicationdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdeposit',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do depósito'),
        ),
    ]
