# Generated by Django 3.2 on 2022-06-26 20:31

from django.db import migrations, models
import investment.interfaces.validators


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0006_applicationdeposit_money_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='date_finished',
            field=models.DateTimeField(blank=True, help_text='Data de encerramento do fundo', null=True, verbose_name='Data de finalização'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='equity_interest',
            field=models.FloatField(blank=True, help_text='Deve ser maior que 0 e menor que 100', null=True, validators=[investment.interfaces.validators.validate_percentage_between_0_100], verbose_name='Participação societária (%)'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='limit_date',
            field=models.DateField(blank=True, help_text='Data limite para encerramento do fundo', null=True, verbose_name='Data limite'),
        ),
    ]
