# Generated by Django 3.2 on 2022-06-27 14:55

from django.db import migrations, models
import django.db.models.deletion
import investment.interfaces.validators


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_auto_20220620_2105'),
        ('crowdfunding', '0007_auto_20220626_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='account_digit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dígito da conta'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='account_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número da conta'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.bank', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='bank_branch_digit',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígito da agência'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='bank_branch_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contato'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Nome da empresa'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='fund_amount',
            field=models.FloatField(blank=True, help_text='Valor referente à participação societária', null=True, validators=[investment.interfaces.validators.validate_null_or_greate_than_zero], verbose_name='Valor total do fundo'),
        ),
    ]
