# Generated by Django 3.2 on 2022-06-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0008_auto_20220627_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='last_notified_deposit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última notificação de depósito'),
        ),
        migrations.AlterField(
            model_name='applicationdeposit',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalização do depósito'),
        ),
    ]
