# Generated by Django 3.2 on 2022-06-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0009_auto_20220627_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdeposit',
            name='requested',
            field=models.BooleanField(default=False, verbose_name='Depósito solicitado'),
        ),
    ]
