# Generated by Django 3.2 on 2022-07-02 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0010_applicationdeposit_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdeposit',
            name='requested',
        ),
    ]
