# Generated by Django 3.2 on 2022-06-06 17:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='Tipo de email')),
                ('prefix', models.CharField(help_text='Prexixo do caminho relativo do arguivo Ex: invitations/email/email_invite', max_length=256, verbose_name='Prefixo')),
                ('subject_template', models.CharField(blank=True, max_length=128, null=True, verbose_name='Assunto')),
                ('subject_tags', models.TextField(blank=True, null=True, verbose_name='Descrição das tags do assunto')),
                ('text_template', models.TextField(verbose_name='Mensagem em texto puro')),
                ('message_template', tinymce.models.HTMLField(verbose_name='Mensagem em rich text')),
                ('message_tags', models.TextField(blank=True, null=True, verbose_name='Descrição das tags do modelo')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
                ('write_error', models.CharField(blank=True, editable=False, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Modelo de email',
                'verbose_name_plural': 'Modelos de email',
            },
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(fields=('prefix',), name='unique_template'),
        ),
    ]
