# Generated by Django 3.2 on 2022-06-06 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investorprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('type', models.CharField(choices=[('PF', 'Pessoa física'), ('PJ', 'Pessoa jurídica')], default='PF', max_length=2, verbose_name='Pessoa física/jurídica')),
                ('display_text', models.CharField(max_length=64, verbose_name='Texto de exibição')),
                ('text', tinymce.models.HTMLField(verbose_name='Texto do contrato')),
                ('instruction', models.TextField(blank=True, help_text='Exclusivo para criação de contrato', null=True, verbose_name='Instruções')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('term_unit', models.CharField(blank=True, choices=[('D', 'Dia'), ('M', 'Mês'), ('Y', 'Ano')], default='M', max_length=1, null=True, verbose_name='Unidade de tempo')),
                ('term_value', models.IntegerField(blank=True, help_text='Deixe em branco para prazo indefinido', null=True, verbose_name='Duração do contrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(max_length=64, verbose_name='Nome de exbição')),
                ('application', models.CharField(max_length=128, verbose_name='Aplicação')),
                ('dashboard_class', models.CharField(max_length=128, verbose_name='Classe do dashboard')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Dashboard',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('display_text', models.CharField(max_length=64, verbose_name='Texto de exibição')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('briefing', tinymce.models.HTMLField(blank=True, help_text='Mostrado ao cliente na oferta de produtos', null=True, verbose_name='Informação resumida para o cliente')),
                ('info', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Informação para o cliente')),
                ('application', models.OneToOneField(help_text='Deve haver somente uma aplicação por produto', on_delete=django.db.models.deletion.CASCADE, to='investment.application', verbose_name='Aplicação')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ProfileProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produto')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investorprofile.profile', verbose_name='Perfil de investimento')),
            ],
            options={
                'verbose_name': 'Perfil do produto',
                'verbose_name_plural': 'Perfís dos produtos',
            },
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.TextField(verbose_name='Contrato')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Renovação automática')),
                ('date_purchased', models.DateTimeField(auto_now_add=True, verbose_name='Data de aquisição')),
                ('date_expire', models.DateTimeField(blank=True, null=True, verbose_name='Vencimento')),
                ('date_cancelled', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Cancelamento')),
                ('notify_before_end', models.BooleanField(default=False, verbose_name='Notificar antes do término do contrato')),
                ('agreement_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.agreementtemplate', verbose_name='Modelo do contrato')),
                ('application_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.applicationaccount', verbose_name='Conta')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto contratado',
                'verbose_name_plural': 'Produtos contratados',
            },
        ),
        migrations.CreateModel(
            name='ProductDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.dashboard', verbose_name='Dashboard')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produto relacionado ao dashboard')),
            ],
            options={
                'verbose_name': 'Dashboard dos produtos',
            },
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produto'),
        ),
        migrations.AddConstraint(
            model_name='productdashboard',
            constraint=models.UniqueConstraint(fields=('product', 'dashboard'), name='unique_product_dashboard'),
        ),
    ]
