# Generated by Django 3.2 on 2022-06-15 12:15

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('display_text', models.CharField(max_length=64, verbose_name='Texto de exibição')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('briefing', tinymce.models.HTMLField(blank=True, help_text='Mostrado ao cliente na oferta de produtos', null=True, verbose_name='Informação resumida para o cliente')),
                ('info', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Informação para o cliente')),
            ],
            options={
                'verbose_name': 'Categoria de produto',
                'verbose_name_plural': 'Categorias de produtos',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='Categoria'),
        ),
    ]
