# Generated by Django 3.2 on 2022-06-15 13:15

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220615_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('display_text', models.CharField(max_length=64, verbose_name='texto de exibição')),
                ('text', tinymce.models.HTMLField(verbose_name='Texto do documento')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Documento da categoria',
                'verbose_name_plural': 'Documentos das categorias',
            },
        ),
    ]
