# Generated by Django 3.2 on 2022-06-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categorydocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='info',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='briefing',
            field=models.TextField(blank=True, help_text='Apenas para controle interno', null=True, verbose_name='Descrição breve da categoria'),
        ),
    ]
