# Generated by Django 3.2 on 2022-06-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220615_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='display_text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='show_title',
            field=models.BooleanField(default=True, verbose_name='Mostrar título'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(help_text='Apenas para controle interno', max_length=64, verbose_name='Nome'),
        ),
    ]
